let ASimAuthenticationCyberArkVault = (disabled: bool = false) {
    CommonSecurityLog
    | where not(disabled)
    | where DeviceVendor == "Cyber-Ark" and DeviceProduct == "Vault"
    | where Activity in ("Logon", "Logoff", "Failure: User Authentication")
    | extend
        EventType = iff(Activity == "Logoff", "Logoff", "Logon"),
        EventResult = iff(Activity startswith "Failure:", "Failure", "Success")
    | extend
        EventResultDetails = iff(EventResult == "Failure", "Other", ""),
        EventSeverity = iff(EventResult == "Failure", "Low", "Informational"),
        TargetUsername = SourceUserName,
        SrcIpAddr = coalesce(SourceIP, SourceTranslatedAddress),
        DvcIpAddr = DeviceAddress
    | extend
        TargetUsernameType = case(
            TargetUsername has "\\", "Windows",
            TargetUsername has "@", "UPN",
            "Simple"
        ),
        Dvc = coalesce(Computer, DvcIpAddr),
        TargetAppName = "CyberArk Vault",
        LogonTarget = "CyberArk Vault",
        EventUid = _ItemId,
        EventCount = 1,
        EventStartTime = TimeGenerated,
        EventEndTime = TimeGenerated,
        EventSchema = "Authentication",
        EventSchemaVersion = "0.1.4",
        EventVendor = "CyberArk",
        EventProduct = "Vault",
        EventSubType = "Remote",
        Type = "CommonSecurityLog"
    | extend
        Dst = Dvc,
        Src = SrcIpAddr
    | project
        TimeGenerated,
        EventStartTime,
        EventEndTime,
        EventCount,
        EventType,
        EventSubType,
        EventResult,
        EventResultDetails,
        EventSeverity,
        EventSchema,
        EventSchemaVersion,
        EventVendor,
        EventProduct,
        EventUid,
        Dvc,
        DvcIpAddr,
        Dst,
        TargetUsername,
        TargetUsernameType,
        TargetAppName,
        LogonTarget,
        SrcIpAddr,
        Src,
        Type
};
